name: Auto Merge gh-pages to main

on:
  push:
    branches:
      - gh-pages

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge gh-pages into main
        run: |
          git checkout main
          git merge gh-pages --no-ff --commit -m "Automated merge from gh-pages to main"
          git push origin main
